;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname ex065) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp")) #f)))
(define-struct movie [title producer year])
; (make-movie title producer year)
; (movie-title m)
; (movie-producer m)
; (movie-year m)
; (movie? m)

(define-struct person [name hair eyes phone])
; (make-person name hair eyes phone)
; (person-name p)
; (person-hair p)
; (person-eyes p)
; (person-phone p)
; (person? p)

(define-struct pet [name number])
; (make-pet name number)
; (pet-name p)
; (pet-number p)
; (pet? p)

(define-struct CD [artist title price])
; (make-CD artist title price)
; (CD-artist c)
; (CD-title c)
; (CD-price c)
; (CD? c)

(define-struct sweater [material size producer])
; (make-sweater material size producer)
; (sweater-material s)
; (sweater-size s)
; (sweater-producer s)
; (sweater? s)
